import { beforeAll, describe, expect, test } from 'vitest'

import { loadConventionalChangelogData } from '../providers/conventional-changelog'

import { mockLoaderContext, mockStore } from './utils'

const store = mockStore()

describe('fs', () => {
  beforeAll(async () => {
    store.clear()

    await loadConventionalChangelogData(
      {
        provider: 'conventional-changelog',
        base: 'test',
        changelog: '../../../fixtures/conventional-changelog/changelog.md',
        enabled: true,
        pagefind: false,
        pageSize: 5,
        title: 'Test',
      },
      mockLoaderContext(store),
    )
  })

  test('loads versions across supported heading levels', () => {
    expect(store.values().map((version) => version.data.title)).toEqual([
      '2.0.0',
      '1.1.0',
      '1.0.2',
      '1.0.1',
      '1.0.0',
      '0.0.1',
    ])
  })

  test('extracts release dates', () => {
    expect(store.values()[0]?.data.date).toEqual(new Date('2025-03-01T00:00:00'))
  })

  test('strips optional release titles', () => {
    expect(store.values()[1]?.data.title).toBe('1.1.0')
  })

  test('loads patch headings generated by the default template', () => {
    const version = store.values()[2]

    expect(version?.data.title).toBe('1.0.2')
    expect(version?.data.date).toEqual(new Date('2025-01-03T00:00:00'))
  })

  test('includes the provider', () => {
    const version = store.values()[0]

    expect(version?.data.provider.name).toBe('conventional-changelog')
    expect(version?.data.provider.label).toBe('Conventional Changelog')
  })

  test('keeps non-version headings in the version body', () => {
    expect(store.values()[3]?.body).toMatchInlineSnapshot(`
      "### Bug Fixes

      * fix an issue
      "
    `)
  })
})
