import type { LoaderContext } from 'astro/loaders'
import { z } from 'astro/zod'

import { loadMarkdownData } from './markdown'

import { ProviderBaseConfigSchema } from '.'

export const ChangesetProviderConfigSchema = ProviderBaseConfigSchema.extend({
  /**
   * The path or URL of the changelog file generated by Changeset to load.
   *
   * When using a path, it should be relative to the root of the Starlight project.
   * When using a URL, it should point to a raw file that contains the changelog, e.g. a GitHub raw URL.
   */
  changelog: z.string(),
  /** The type of provider used to load the changelog, `changeset` in this case. */
  provider: z.literal('changeset'),
})

const provider = { name: 'changeset', label: 'Changeset' } as const

export async function loadChangesetData(config: ChangesetProviderConfig, context: LoaderContext) {
  await loadMarkdownData({ ...config, provider }, context)
}

type ChangesetProviderConfig = z.output<typeof ChangesetProviderConfigSchema>
