import type { LoaderContext } from 'astro/loaders'
import { z } from 'astro/zod'

import { loadMarkdownData, type MarkdownProviderConfig } from './markdown'

import { ProviderBaseConfigSchema } from '.'

export const ConventionalChangelogProviderConfigSchema = ProviderBaseConfigSchema.extend({
  /**
   * The path or URL of the changelog file generated by Conventional Changelog to load.
   *
   * When using a path, it should be relative to the root of the Starlight project.
   * When using a URL, it should point to a raw file that contains the changelog, e.g. a GitHub raw URL.
   */
  changelog: z.string(),
  /** The type of provider used to load the changelog, `conventional-changelog` in this case. */
  provider: z.literal('conventional-changelog'),
})

const provider: MarkdownProviderConfig['provider'] = {
  name: 'conventional-changelog',
  label: 'Conventional Changelog',
}
const versionHeadingRegex =
  /^(?<version>v?\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?)(?: "[^"]*")?(?: \((?<date>\d{4}-\d{2}-\d{2})\))?$/
const markdown: MarkdownProviderConfig['markdown'] = {
  isVersionHeading({ title }) {
    return matchVersionHeading(title) !== null
  },
  process({ title }) {
    const match = matchVersionHeading(title)
    const date = match?.groups?.['date']

    return {
      title: match?.groups?.['version'] ?? title,
      ...(date ? { date: new Date(`${date}T00:00:00`) } : {}),
    }
  },
  versionHeadingLevel: [1, 2, 3],
}

function matchVersionHeading(title: string) {
  return versionHeadingRegex.exec(title.replace(/^<small>(.*)<\/small>$/, '$1'))
}

export async function loadConventionalChangelogData(
  config: ConventionalChangelogProviderConfig,
  context: LoaderContext,
) {
  await loadMarkdownData({ ...config, markdown, provider }, context)
}

type ConventionalChangelogProviderConfig = z.output<typeof ConventionalChangelogProviderConfigSchema>
