import starlight from '@astrojs/starlight'
import { defineConfig } from 'astro/config'
import starlightChangelogs from 'starlight-changelogs'

export default defineConfig({
  integrations: [
    starlight({
      description: '// TODO(HiDeoo) ',
      editLink: {
        baseUrl: 'https://github.com/HiDeoo/starlight-changelogs/edit/main/docs/',
      },
      plugins: [starlightChangelogs()],
      // sidebar: [
      //   {
      //     label: "Start Here",
      //     items: ["getting-started", "configuration"],
      //   },
      //   {
      //     label: "Guides",
      //     items: ["guides/custom-highlights"],
      //   },
      //   {
      //     label: "Resources",
      //     items: [{ label: "Plugins and Tools", slug: "resources/starlight" }],
      //   },
      //   {
      //     label: "Tests",
      //     items: [
      //       "tests/not-a-draft",
      //       { slug: "tests/not-a-draft" },
      //       { label: "Not a Draft", link: "/tests/not-a-draft/" },
      //       "tests/draft",
      //       { slug: "tests/draft" },
      //       { label: "Draft", link: "/tests/draft/" },
      //       {
      //         label: "Nested",
      //         items: [
      //           "tests/nested/not-a-draft",
      //           { slug: "tests/nested/not-a-draft" },
      //           { label: "Not a Draft", link: "/tests/nested/not-a-draft/" },
      //           "tests/nested/draft",
      //           { slug: "tests/nested/draft" },
      //           { label: "Draft", link: "/tests/nested/draft/" },
      //         ],
      //       },
      //       {
      //         label: "Long",
      //         items: [
      //           "tests/long/not-a-draft",
      //           { slug: "tests/long/not-a-draft" },
      //           { label: "Not a Draft", link: "/tests/long/not-a-draft/" },
      //           "tests/long/draft",
      //           { slug: "tests/long/draft" },
      //           { label: "Draft", link: "/tests/long/draft/" },
      //         ],
      //       },
      //       {
      //         label: "Autogenerated",
      //         autogenerate: { directory: "tests/autogenerated" },
      //       },
      //     ],
      //   },
      // ],
      social: [
        {
          href: 'https://bsky.app/profile/hideoo.dev',
          icon: 'blueSky',
          label: 'Bluesky',
        },
        {
          href: 'https://github.com/HiDeoo/starlight-changelogs',
          icon: 'github',
          label: 'GitHub',
        },
      ],
      title: 'Starlight Changelogs',
    }),
  ],
  site: 'https://starlight-changelogs.netlify.app/',
  trailingSlash: 'always',
})
